"""Elementwise kernels, one module per category.

Each module is named after the ``ops/elementwise`` module holding the ops it serves.
The templates every kernel here is built from are in ``_base``; the dtype helpers
they share are in ``_dtype``.
"""

from tileops.kernels.elementwise._base import BinaryKernel, FusedGatedKernel, UnaryKernel
from tileops.kernels.elementwise._broadcast import coalesce_broadcast_dims
from tileops.kernels.elementwise.activations import (
    EluFwdKernel,
    GeluAndMulFwdKernel,
    GeluFwdKernel,
    GeluTanhAndMulFwdKernel,
    GeluTanhFwdKernel,
    HardsigmoidFwdKernel,
    HardswishFwdKernel,
    HardtanhFwdKernel,
    LeakyReluFwdKernel,
    MishFwdKernel,
    ReluFwdKernel,
    SeluFwdKernel,
    SigmoidFwdKernel,
    SiluAndMulFwdKernel,
    SiluFwdKernel,
    SoftplusFwdKernel,
    TanhFwdKernel,
)
from tileops.kernels.elementwise.alibi import AlibiFwdKernel
from tileops.kernels.elementwise.arithmetic import (
    AddFwdKernel,
    DivFwdKernel,
    DivTruncFwdKernel,
    FloorDivideFwdKernel,
    LerpFwdKernel,
    LerpTensorFwdKernel,
    MaximumFwdKernel,
    MinimumFwdKernel,
    MulFwdKernel,
    PowFwdKernel,
    RemainderFwdKernel,
    SubFwdKernel,
)
from tileops.kernels.elementwise.bitwise import (
    BitwiseAndBoolStorageFwdKernel,
    BitwiseAndFwdKernel,
    BitwiseNotFwdKernel,
    BitwiseOrBoolStorageFwdKernel,
    BitwiseOrFwdKernel,
    BitwiseXorBoolStorageFwdKernel,
    BitwiseXorFwdKernel,
)
from tileops.kernels.elementwise.clamp import ClampFwdKernel, ClampTensorFwdKernel
from tileops.kernels.elementwise.comparison import (
    AlwaysFalseFwdKernel,
    AlwaysTrueFwdKernel,
    EqBoolStorageFwdKernel,
    EqFwdKernel,
    GeBoolStorageFwdKernel,
    GeFwdKernel,
    GtBoolStorageFwdKernel,
    GtFwdKernel,
    IsfiniteFwdKernel,
    IsinfFwdKernel,
    IsnanFwdKernel,
    LeBoolStorageFwdKernel,
    LeFwdKernel,
    LtBoolStorageFwdKernel,
    LtFwdKernel,
    NeBoolStorageFwdKernel,
    NeFwdKernel,
)
from tileops.kernels.elementwise.logical import (
    LogicalAndBoolStorageFwdKernel,
    LogicalAndFwdKernel,
    LogicalNotBoolStorageFwdKernel,
    LogicalNotFwdKernel,
    LogicalOrBoolStorageFwdKernel,
    LogicalOrFwdKernel,
)
from tileops.kernels.elementwise.masked_fill import (
    MaskedFillFwdKernel,
    MaskedFillTensorValueFwdKernel,
)
from tileops.kernels.elementwise.math_unary import (
    AbsFwdKernel,
    AbsIntFwdKernel,
    CeilFwdKernel,
    CosFwdKernel,
    ErfFwdKernel,
    ExpFwdKernel,
    Expm1FwdKernel,
    FloorFwdKernel,
    IntIdentityFwdKernel,
    Log1pFwdKernel,
    LogFwdKernel,
    NegFwdKernel,
    NegIntFwdKernel,
    ReciprocalFwdKernel,
    RoundDecimalsFwdKernel,
    RoundFwdKernel,
    RsqrtFwdKernel,
    SignFwdKernel,
    SignIntFwdKernel,
    SinFwdKernel,
    SqrtFwdKernel,
    TruncFwdKernel,
)
from tileops.kernels.elementwise.nan_to_num import NanToNumFwdKernel
from tileops.kernels.elementwise.prelu import PreluFwdKernel
from tileops.kernels.elementwise.sinusoidal import SinusoidalFwdKernel
from tileops.kernels.elementwise.where import WhereFwdKernel

__all__ = [
    "AbsFwdKernel",
    "AbsIntFwdKernel",
    "AddFwdKernel",
    "AlibiFwdKernel",
    "AlwaysFalseFwdKernel",
    "AlwaysTrueFwdKernel",
    "BinaryKernel",
    "BitwiseAndBoolStorageFwdKernel",
    "BitwiseAndFwdKernel",
    "BitwiseNotFwdKernel",
    "BitwiseOrBoolStorageFwdKernel",
    "BitwiseOrFwdKernel",
    "BitwiseXorBoolStorageFwdKernel",
    "BitwiseXorFwdKernel",
    "CeilFwdKernel",
    "ClampFwdKernel",
    "ClampTensorFwdKernel",
    "CosFwdKernel",
    "DivFwdKernel",
    "DivTruncFwdKernel",
    "EluFwdKernel",
    "EqBoolStorageFwdKernel",
    "EqFwdKernel",
    "ErfFwdKernel",
    "ExpFwdKernel",
    "Expm1FwdKernel",
    "FloorDivideFwdKernel",
    "FloorFwdKernel",
    "FusedGatedKernel",
    "GeBoolStorageFwdKernel",
    "GeFwdKernel",
    "GeluAndMulFwdKernel",
    "GeluFwdKernel",
    "GeluTanhAndMulFwdKernel",
    "GeluTanhFwdKernel",
    "GtBoolStorageFwdKernel",
    "GtFwdKernel",
    "HardsigmoidFwdKernel",
    "HardswishFwdKernel",
    "HardtanhFwdKernel",
    "IntIdentityFwdKernel",
    "IsfiniteFwdKernel",
    "IsinfFwdKernel",
    "IsnanFwdKernel",
    "LeBoolStorageFwdKernel",
    "LeFwdKernel",
    "LeakyReluFwdKernel",
    "LerpFwdKernel",
    "LerpTensorFwdKernel",
    "Log1pFwdKernel",
    "LogFwdKernel",
    "LogicalAndBoolStorageFwdKernel",
    "LogicalAndFwdKernel",
    "LogicalNotBoolStorageFwdKernel",
    "LogicalNotFwdKernel",
    "LogicalOrBoolStorageFwdKernel",
    "LogicalOrFwdKernel",
    "LtBoolStorageFwdKernel",
    "LtFwdKernel",
    "MaskedFillFwdKernel",
    "MaskedFillTensorValueFwdKernel",
    "MaximumFwdKernel",
    "MinimumFwdKernel",
    "MishFwdKernel",
    "MulFwdKernel",
    "NanToNumFwdKernel",
    "NeBoolStorageFwdKernel",
    "NeFwdKernel",
    "NegFwdKernel",
    "NegIntFwdKernel",
    "PowFwdKernel",
    "PreluFwdKernel",
    "ReciprocalFwdKernel",
    "ReluFwdKernel",
    "RemainderFwdKernel",
    "RoundDecimalsFwdKernel",
    "RoundFwdKernel",
    "RsqrtFwdKernel",
    "SeluFwdKernel",
    "SigmoidFwdKernel",
    "SignFwdKernel",
    "SignIntFwdKernel",
    "SiluAndMulFwdKernel",
    "SiluFwdKernel",
    "SinFwdKernel",
    "SinusoidalFwdKernel",
    "SoftplusFwdKernel",
    "SqrtFwdKernel",
    "SubFwdKernel",
    "TanhFwdKernel",
    "TruncFwdKernel",
    "UnaryKernel",
    "WhereFwdKernel",
    "coalesce_broadcast_dims",
]
