"""Which kernel serves each op on this target. The nv backend's own data.

Values are ``"module:Class"`` strings rather than imported classes, so importing this
backend costs nothing: a kernel module — and TileLang with it — is imported only when the
op it serves is first built.

The keys under an op are that op's *roles*, a naming space private to this backend. The
neutral protocol never sees them: it asks a target for a kernel and takes what it gets.
"""

BINDINGS: dict[str, dict[str, str]] = {
    'AbsFwdOp': {'abs': 'tileops.kernels.elementwise:AbsFwdKernel'},
    'AdaLayerNormFwdOp': {'ada_layer_norm': 'tileops.kernels.norm.ada_layer_norm:AdaLayerNormKernel'},
    'AdaLayerNormZeroFwdOp': {'ada_layer_norm': 'tileops.kernels.norm.ada_layer_norm:AdaLayerNormKernel'},
    'AdaptiveAvgPool2dFwdOp': {'adaptive_avg_pool2d_kernel': 'tileops.kernels.pool.adaptive_avg_pool2d:AdaptiveAvgPool2dKernel'},
    'AdaptiveMaxPool2dFwdOp': {'adaptive_max_pool2d_kernel': 'tileops.kernels.pool.adaptive_max_pool2d:AdaptiveMaxPool2dKernel'},
    'AdaptiveMaxPool2dIndicesFwdOp': {'adaptive_max_pool2d_with_indices_kernel': 'tileops.kernels.pool.adaptive_max_pool2d:AdaptiveMaxPool2dWithIndicesKernel'},
    'AddFwdOp': {'add': 'tileops.kernels.elementwise:AddFwdKernel'},
    'AlibiFwdOp': {'alibi': 'tileops.kernels.elementwise:AlibiFwdKernel'},
    'AllFwdOp': {'logical_reduce': 'tileops.kernels.reduction.logical_reduce:LogicalReduceKernel'},
    'AmaxFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'AminFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'AnyFwdOp': {'logical_reduce': 'tileops.kernels.reduction.logical_reduce:LogicalReduceKernel'},
    'ArgmaxFwdOp': {'argreduce': 'tileops.kernels.reduction.argreduce:ArgreduceKernel'},
    'ArgminFwdOp': {'argreduce': 'tileops.kernels.reduction.argreduce:ArgreduceKernel'},
    'AvgPool1dFwdOp': {
        'avg_pool1d_kernel': 'tileops.kernels.pool.avg_pool1d:AvgPool1dKernel',
        'avg_pool1d_spatial_kernel': 'tileops.kernels.pool.avg_pool1d:AvgPool1dSpatialKernel',
    },
    'AvgPool2dFwdOp': {'avg_pool2d_kernel': 'tileops.kernels.pool.avg_pool2d:AvgPool2dKernel'},
    'AvgPool3dFwdOp': {
        'avg_pool3d_kernel': 'tileops.kernels.pool.avg_pool3d:AvgPool3dKernel',
        'avg_pool3d_spatial_kernel': 'tileops.kernels.pool.avg_pool3d:AvgPool3dSpatialKernel',
    },
    'BatchNormBwdOp': {'bwd_kernel': 'tileops.kernels.norm.batch_norm:BatchNormBwdKernel'},
    'BatchNormFwdOp': {
        'fwd_infer_kernel': 'tileops.kernels.norm.batch_norm:BatchNormFwdInferKernel',
        'fwd_train_kernel': 'tileops.kernels.norm.batch_norm:BatchNormFwdTrainKernel',
    },
    'BitwiseAndFwdOp': {'bitwise_and': 'tileops.kernels.elementwise:BitwiseAndFwdKernel'},
    'BitwiseNotFwdOp': {'bitwise_not': 'tileops.kernels.elementwise:BitwiseNotFwdKernel'},
    'BitwiseOrFwdOp': {'bitwise_or': 'tileops.kernels.elementwise:BitwiseOrFwdKernel'},
    'BitwiseXorFwdOp': {'bitwise_xor': 'tileops.kernels.elementwise:BitwiseXorFwdKernel'},
    'BmmFp8Op': {'bmm_fp8_kernel': 'tileops.kernels.bmm:BmmFp8Kernel'},
    'BmmFwdOp': {'bmm_kernel': 'tileops.kernels.bmm:BmmKernel'},
    'CBProducerOp': {'cb_producer': 'tileops.kernels.mamba.cb_producer:CBProducerKernel'},
    'CeilFwdOp': {'ceil': 'tileops.kernels.elementwise:CeilFwdKernel'},
    'ClampFwdOp': {'clamp_tensor': 'tileops.kernels.elementwise:ClampTensorFwdKernel'},
    'ClampMaxFwdOp': {'clamp_tensor': 'tileops.kernels.elementwise:ClampTensorFwdKernel'},
    'ClampMinFwdOp': {'clamp_tensor': 'tileops.kernels.elementwise:ClampTensorFwdKernel'},
    'ClampScalarFwdOp': {'clamp': 'tileops.kernels.elementwise:ClampFwdKernel'},
    'Conv1dBiasFwdOp': {
        'conv1d_kernel': 'tileops.kernels.convolution:Conv1dKernel',
        'conv1d_pointwise_kernel': 'tileops.kernels.convolution:Conv1dPointwiseKernel',
        'group_conv1d_kernel': 'tileops.kernels.convolution:GroupConv1dKernel',
    },
    'Conv1dFwdOp': {
        'conv1d_kernel': 'tileops.kernels.convolution:Conv1dKernel',
        'conv1d_pointwise_kernel': 'tileops.kernels.convolution:Conv1dPointwiseKernel',
        'group_conv1d_kernel': 'tileops.kernels.convolution:GroupConv1dKernel',
    },
    'Conv2dBiasFwdOp': {
        'conv2d_1x1_kernel': 'tileops.kernels.convolution:Conv2d1x1Kernel',
        'conv2d_kernel': 'tileops.kernels.convolution:Conv2dKernel',
        'group_conv2d_kernel': 'tileops.kernels.convolution:GroupConv2dKernel',
    },
    'Conv2dFwdOp': {
        'conv2d_1x1_kernel': 'tileops.kernels.convolution:Conv2d1x1Kernel',
        'conv2d_kernel': 'tileops.kernels.convolution:Conv2dKernel',
        'group_conv2d_kernel': 'tileops.kernels.convolution:GroupConv2dKernel',
    },
    'Conv3dBiasFwdOp': {
        'conv3d_kernel': 'tileops.kernels.convolution:Conv3dKernel',
        'group_conv3d_kernel': 'tileops.kernels.convolution:GroupConv3dKernel',
    },
    'Conv3dFwdOp': {
        'conv3d_kernel': 'tileops.kernels.convolution:Conv3dKernel',
        'group_conv3d_kernel': 'tileops.kernels.convolution:GroupConv3dKernel',
    },
    'CosFwdOp': {'cos': 'tileops.kernels.elementwise:CosFwdKernel'},
    'CountNonzeroFwdOp': {'logical_reduce': 'tileops.kernels.reduction.logical_reduce:LogicalReduceKernel'},
    'CumprodFwdOp': {'cumulative_fwd': 'tileops.kernels.reduction.cumulative:CumulativeKernel'},
    'CumsumFwdOp': {'cumulative_fwd': 'tileops.kernels.reduction.cumulative:CumulativeKernel'},
    'DaCumsumBiasFwdOp': {'da_cumsum_fwd': 'tileops.kernels.mamba.da_cumsum:DaCumsumFwdKernel'},
    'DaCumsumFwdOp': {'da_cumsum_fwd': 'tileops.kernels.mamba.da_cumsum:DaCumsumFwdKernel'},
    'DeepSeekSparseAttentionDecodeWithKVCacheFwdOp': {'sparse_mla_kernel': 'tileops.kernels.attention.deepseek_dsa_decode:SparseMlaKernel'},
    'DeltaNetDecodeOp': {
        'DeltaNetDecodeFP32Kernel': 'tileops.kernels.deltanet_recurrence:DeltaNetDecodeFP32Kernel',
        'DeltaNetDecodeKernel': 'tileops.kernels.deltanet_recurrence:DeltaNetDecodeKernel',
        'DeltaNetDecodeRawCudaFlaStyleKernel': 'tileops.kernels.deltanet_recurrence:DeltaNetDecodeRawCudaFlaStyleKernel',
    },
    'DivFwdOp': {'div': 'tileops.kernels.elementwise:DivFwdKernel'},
    'DropoutOp': {'dropout': 'tileops.kernels.dropout:DropoutKernel'},
    'EluFwdOp': {'elu': 'tileops.kernels.elementwise:EluFwdKernel'},
    'EngramDecodeOp': {'engram_decode': 'tileops.kernels.engram.engram_decode:EngramDecodeKernel'},
    'EngramGateConvBwdOp': {'engram_gate_conv_bwd': 'tileops.kernels.engram.engram_bwd:EngramGateConvBwdKernel'},
    'EngramGateConvFwdOp': {'engram_gate_conv_fwd': 'tileops.kernels.engram.engram_fwd:EngramGateConvFwdKernel'},
    'EqFwdOp': {'eq': 'tileops.kernels.elementwise:EqFwdKernel'},
    'ErfFwdOp': {'erf': 'tileops.kernels.elementwise:ErfFwdKernel'},
    'ExpFwdOp': {'exp': 'tileops.kernels.elementwise:ExpFwdKernel'},
    'Expm1FwdOp': {'expm1': 'tileops.kernels.elementwise:Expm1FwdKernel'},
    'FFTC2COp': {'fft_c2c_kernel': 'tileops.kernels.fft:FFTC2CKernel'},
    'FP8LightningIndexerOp': {'fp8_lightning_indexer_kernel': 'tileops.kernels.fp8_lightning_indexer:FP8LightningIndexerKernel'},
    'FP8QuantOp': {'fp8_quant_kernel': 'tileops.kernels.fp8_quant:FP8QuantKernel'},
    'FloorDivideFwdOp': {'floor_divide': 'tileops.kernels.elementwise:FloorDivideFwdKernel'},
    'FloorFwdOp': {'floor': 'tileops.kernels.elementwise:FloorFwdKernel'},
    'FusedAddLayerNormFwdOp': {'fused_add_layer_norm': 'tileops.kernels.norm.fused_add_norm:FusedAddLayerNormKernel'},
    'FusedAddRMSNormFwdOp': {'fused_add_rms_norm': 'tileops.kernels.norm.fused_add_norm:FusedAddRMSNormKernel'},
    'FusedMoEExpertsNopadPersistent3WGFwdOp': {
        'gelu_and_mul': 'tileops.kernels.elementwise:GeluAndMulFwdKernel',
        'moe_grouped_gemm_kernel': 'tileops.kernels.grouped_gemm.grouped_gemm_persistent_3wg:GroupedGemmPersistent3WGKernel',
        'permute_nopad_kernel': 'tileops.kernels.moe.permute_nopad:MoePermuteNopadKernel',
        'silu_and_mul': 'tileops.kernels.elementwise:SiluAndMulFwdKernel',
        'unpermute_kernel': 'tileops.kernels.moe.unpermute:MoeUnpermuteKernel',
    },
    'FusedMoeFwdCbFwdOp': {
        'fused_topk_kernel': 'tileops.kernels.moe.fused_topk:FusedTopKKernel',
        'gelu_and_mul': 'tileops.kernels.elementwise:GeluAndMulFwdKernel',
        'moe_grouped_gemm_kernel': 'tileops.kernels.grouped_gemm.grouped_gemm_persistent_3wg:GroupedGemmPersistent3WGKernel',
        'permute_nopad_kernel': 'tileops.kernels.moe.permute_nopad:MoePermuteNopadKernel',
        'silu_and_mul': 'tileops.kernels.elementwise:SiluAndMulFwdKernel',
        'unpermute_kernel': 'tileops.kernels.moe.unpermute:MoeUnpermuteKernel',
    },
    'FusedMoeFwdOp': {
        'fused_topk_kernel': 'tileops.kernels.moe.fused_topk:FusedTopKKernel',
        'gelu_and_mul': 'tileops.kernels.elementwise:GeluAndMulFwdKernel',
        'moe_grouped_gemm_kernel': 'tileops.kernels.grouped_gemm.grouped_gemm_persistent_3wg:GroupedGemmPersistent3WGKernel',
        'permute_nopad_kernel': 'tileops.kernels.moe.permute_nopad:MoePermuteNopadKernel',
        'silu_and_mul': 'tileops.kernels.elementwise:SiluAndMulFwdKernel',
        'unpermute_kernel': 'tileops.kernels.moe.unpermute:MoeUnpermuteKernel',
    },
    'GLADecodeOp': {
        'GLADecodeFP32Kernel': 'tileops.kernels.gla_recurrence:GLADecodeFP32Kernel',
        'GLADecodeKernel': 'tileops.kernels.gla_recurrence:GLADecodeKernel',
    },
    'GatedDeltaNetDecodeOp': {
        'GatedDeltaNetDecodeFP32Kernel': 'tileops.kernels.gated_deltanet_recurrence:GatedDeltaNetDecodeFP32Kernel',
        'GatedDeltaNetDecodeKernel': 'tileops.kernels.gated_deltanet_recurrence:GatedDeltaNetDecodeKernel',
        'GatedDeltaNetDecodeRawCudaFlaStyleKernel': 'tileops.kernels.gated_deltanet_recurrence:GatedDeltaNetDecodeRawCudaFlaStyleKernel',
    },
    'GatedDeltaNetPrefillFwdOp': {'GatedDeltaNetPrefillFwdKernel': 'tileops.kernels.gated_deltanet.gated_deltanet_prefill:GatedDeltaNetPrefillFwdKernel'},
    'GeFwdOp': {'ge': 'tileops.kernels.elementwise:GeFwdKernel'},
    'GeluAndMulFwdOp': {'gelu_and_mul': 'tileops.kernels.elementwise:GeluAndMulFwdKernel'},
    'GeluFwdOp': {'gelu': 'tileops.kernels.elementwise:GeluFwdKernel'},
    'GeluTanhAndMulFwdOp': {'gelu_tanh_and_mul': 'tileops.kernels.elementwise:GeluTanhAndMulFwdKernel'},
    'GemmFp8Op': {
        'gemm_fp8_block_scaled_kernel': 'tileops.kernels.gemm:GemmFp8BlockScaledKernel',
        'gemm_fp8_epilogue_kernel': 'tileops.kernels.gemm:GemmFp8EpilogueKernel',
    },
    'GemmOp': {
        'gemm_kernel': 'tileops.kernels.gemm:GemmKernel',
        'gemv_kernel': 'tileops.kernels.gemm:GemvKernel',
    },
    'GemmW4A16Op': {'gemm_w4a16_kernel': 'tileops.kernels.gemm_w4a16:GemmW4A16Kernel'},
    'GroupNormFwdOp': {'group_norm': 'tileops.kernels.norm.group_norm:GroupNormKernel'},
    'GroupNormNoAffineFwdOp': {'group_norm_no_affine': 'tileops.kernels.norm.group_norm:GroupNormNoAffineKernel'},
    'GroupedGemmOp': {'grouped_gemm_kernel': 'tileops.kernels.grouped_gemm.grouped_gemm:GroupedGemmKernel'},
    'GroupedQueryAttentionBwdOp': {
        'gqa_bwd_kernel': 'tileops.kernels.attention.gqa_bwd:GQABwdWgmmaPipelinedKernel',
        'gqa_bwd_preprocess_kernel': 'tileops.kernels.attention.gqa_bwd:FlashAttnBwdPreprocessKernel',
    },
    'GroupedQueryAttentionDecodePagedWithKVCacheFwdOp': {
        'gqa_decode_paged_bs1_kernel': 'tileops.kernels.attention.gqa_decode_bs1_paged:GQADecodePagedBs1Kernel',
        'gqa_decode_paged_kernel': 'tileops.kernels.attention.gqa_decode_paged:GQADecodePagedKernel',
    },
    'GroupedQueryAttentionDecodeWithKVCacheFwdOp': {
        'gqa_decode_bs1_kernel': 'tileops.kernels.attention.gqa_decode_bs1:GQADecodeBs1Kernel',
        'gqa_decode_kernel': 'tileops.kernels.attention.gqa_decode:GQADecodeKernel',
    },
    'GroupedQueryAttentionFwdOp': {
        'gqa_prefill_causal_fwd_kernel': 'tileops.kernels.attention.gqa_prefill_fwd_ws:GQAPrefillFwdWsPersistentCausalKernel',
        'gqa_prefill_fwd_kernel': 'tileops.kernels.attention.gqa_fwd:GQAPrefillFwdKernel',
        'gqa_prefill_square_fwd_kernel': 'tileops.kernels.attention.gqa_fwd_ws:GQAFwdWsPersistentCausalKernel',
    },
    'GroupedQueryAttentionPrefillFwdOp': {
        'gqa_prefill_causal_fwd_kernel': 'tileops.kernels.attention.gqa_prefill_fwd_ws:GQAPrefillFwdWsPersistentCausalKernel',
        'gqa_prefill_fp8_tensor_core_fwd_kernel': 'tileops.kernels.attention.gqa_fwd_fp8:GQAFwdFP8Fa3ContractPtxAccBN224WsTmaVKernel',
        'gqa_prefill_fwd_kernel': 'tileops.kernels.attention.gqa_fwd:GQAPrefillFwdKernel',
        'gqa_prefill_square_fwd_kernel': 'tileops.kernels.attention.gqa_fwd_ws:GQAFwdWsPersistentCausalKernel',
        'gqa_prefill_varlen_fwd_kernel': 'tileops.kernels.attention.gqa_prefill_varlen_fwd:GQAPrefillVarlenFwdKernel',
        'gqa_sliding_window_varlen_fwd_kernel': 'tileops.kernels.attention.gqa_sliding_window_varlen_fwd:GQASlidingWindowVarlenFwdWgmmaPipelinedKernel',
    },
    'GroupedQueryAttentionPrefillPagedWithKVCacheFwdOp': {
        'gqa_prefill_paged_with_fp8_kv_cache_fwd_kernel': 'tileops.kernels.attention.gqa_fwd:GQAPrefillPagedWithFP8KVCacheFwdKernel',
        'gqa_prefill_paged_with_kv_cache_fwd_kernel': 'tileops.kernels.attention.gqa_fwd:GQAPrefillPagedWithKVCacheFwdKernel',
        'gqa_prefill_paged_with_kv_cache_rope_append_kernel': 'tileops.kernels.attention.gqa_fwd:GQAPrefillPagedWithKVCacheRopeAppendKernel',
        'gqa_prefill_paged_with_kv_cache_rope_fwd_kernel': 'tileops.kernels.attention.gqa_fwd:GQAPrefillPagedWithKVCacheRopeFwdKernel',
    },
    'GroupedQueryAttentionSlidingWindowFwdOp': {'gqa_sliding_window_fwd_kernel': 'tileops.kernels.attention.gqa_sliding_window_fwd:GQASlidingWindowFwdWgmmaPipelinedKernel'},
    'GroupedQueryAttentionSlidingWindowVarlenFwdOp': {'gqa_sliding_window_varlen_fwd_kernel': 'tileops.kernels.attention.gqa_sliding_window_varlen_fwd:GQASlidingWindowVarlenFwdWgmmaPipelinedKernel'},
    'GtFwdOp': {'gt': 'tileops.kernels.elementwise:GtFwdKernel'},
    'HardsigmoidFwdOp': {'hardsigmoid': 'tileops.kernels.elementwise:HardsigmoidFwdKernel'},
    'HardswishFwdOp': {'hardswish': 'tileops.kernels.elementwise:HardswishFwdKernel'},
    'HardtanhFwdOp': {'hardtanh': 'tileops.kernels.elementwise:HardtanhFwdKernel'},
    'InfNormFwdOp': {'vector_norm': 'tileops.kernels.reduction.vector_norm:VectorNormKernel'},
    'InstanceNormFwdOp': {'group_norm': 'tileops.kernels.norm.group_norm:GroupNormKernel'},
    'InstanceNormNoAffineFwdOp': {'instance_norm_no_affine': 'tileops.kernels.norm.instance_norm:InstanceNormNoAffineKernel'},
    'IsfiniteFwdOp': {'isfinite': 'tileops.kernels.elementwise:IsfiniteFwdKernel'},
    'IsinfFwdOp': {'isinf': 'tileops.kernels.elementwise:IsinfFwdKernel'},
    'IsnanFwdOp': {'isnan': 'tileops.kernels.elementwise:IsnanFwdKernel'},
    'L1NormFwdOp': {'vector_norm': 'tileops.kernels.reduction.vector_norm:VectorNormKernel'},
    'L2NormFwdOp': {'vector_norm': 'tileops.kernels.reduction.vector_norm:VectorNormKernel'},
    'LayerNormFwdOp': {'layer_norm': 'tileops.kernels.norm.layer_norm:LayerNormKernel'},
    'LeFwdOp': {'le': 'tileops.kernels.elementwise:LeFwdKernel'},
    'LeakyReluFwdOp': {'leaky_relu': 'tileops.kernels.elementwise:LeakyReluFwdKernel'},
    'LerpFwdOp': {'lerp': 'tileops.kernels.elementwise:LerpFwdKernel'},
    'LerpTensorFwdOp': {'lerp_tensor': 'tileops.kernels.elementwise:LerpTensorFwdKernel'},
    'Log1pFwdOp': {'log1p': 'tileops.kernels.elementwise:Log1pFwdKernel'},
    'LogFwdOp': {'log': 'tileops.kernels.elementwise:LogFwdKernel'},
    'LogSoftmaxFwdOp': {'softmax_fwd': 'tileops.kernels.reduction.softmax:SoftmaxKernel'},
    'LogSumExpFwdOp': {'logsumexp_fwd': 'tileops.kernels.reduction.logsumexp:LogSumExpKernel'},
    'LogicalAndFwdOp': {'logical_and': 'tileops.kernels.elementwise:LogicalAndFwdKernel'},
    'LogicalNotFwdOp': {'logical_not': 'tileops.kernels.elementwise:LogicalNotFwdKernel'},
    'LogicalOrFwdOp': {'logical_or': 'tileops.kernels.elementwise:LogicalOrFwdKernel'},
    'LtFwdOp': {'lt': 'tileops.kernels.elementwise:LtFwdKernel'},
    'MHCPostOp': {'mhc_post_kernel': 'tileops.kernels.mhc.mhc_post:MHCPostKernel'},
    'MHCPreOp': {'mhc_pre_kernel': 'tileops.kernels.mhc.mhc_pre:MHCPreKernel'},
    'MaskedFillFwdOp': {'masked_fill_tensor_value': 'tileops.kernels.elementwise:MaskedFillTensorValueFwdKernel'},
    'MaskedFillScalarFwdOp': {'masked_fill': 'tileops.kernels.elementwise:MaskedFillFwdKernel'},
    'MaxPool1dFwdOp': {'max_pool1d_kernel': 'tileops.kernels.pool.max_pool1d:MaxPool1dKernel'},
    'MaxPool1dIndicesFwdOp': {'max_pool1d_with_indices_kernel': 'tileops.kernels.pool.max_pool1d:MaxPool1dWithIndicesKernel'},
    'MaxPool2dFwdOp': {'max_pool2d_kernel': 'tileops.kernels.pool.max_pool2d:MaxPool2dKernel'},
    'MaxPool2dIndicesFwdOp': {'max_pool2d_with_indices_kernel': 'tileops.kernels.pool.max_pool2d:MaxPool2dWithIndicesKernel'},
    'MaxPool3dFwdOp': {'max_pool3d_kernel': 'tileops.kernels.pool.max_pool3d:MaxPool3dKernel'},
    'MaxPool3dIndicesFwdOp': {'max_pool3d_with_indices_kernel': 'tileops.kernels.pool.max_pool3d:MaxPool3dWithIndicesKernel'},
    'MaximumFwdOp': {'maximum': 'tileops.kernels.elementwise:MaximumFwdKernel'},
    'MeanFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'MinimumFwdOp': {'minimum': 'tileops.kernels.elementwise:MinimumFwdKernel'},
    'MishFwdOp': {'mish': 'tileops.kernels.elementwise:MishFwdKernel'},
    'MoeGroupedGemmNopadFwdOp': {'moe_grouped_gemm_kernel': 'tileops.kernels.moe.moe_grouped_gemm_nopad:MoeGroupedGemmNopadKernel'},
    'MoePermuteAlignFwdOp': {'permute_align_kernel': 'tileops.kernels.moe.permute_align:MoePermuteAlignKernel'},
    'MoePermuteNopadFwdOp': {'permute_nopad_kernel': 'tileops.kernels.moe.permute_nopad:MoePermuteNopadKernel'},
    'MoeUnpermuteFwdOp': {'unpermute_kernel': 'tileops.kernels.moe.unpermute:MoeUnpermuteKernel'},
    'MulFwdOp': {'mul': 'tileops.kernels.elementwise:MulFwdKernel'},
    'MultiHeadAttentionBwdOp': {
        'gqa_bwd_kernel': 'tileops.kernels.attention.gqa_bwd:GQABwdWgmmaPipelinedKernel',
        'gqa_bwd_preprocess_kernel': 'tileops.kernels.attention.gqa_bwd:FlashAttnBwdPreprocessKernel',
    },
    'MultiHeadAttentionDecodePagedWithKVCacheFwdOp': {'mha_decode_paged_kernel': 'tileops.kernels.attention.mha_decode_paged:MHADecodePagedKernel'},
    'MultiHeadAttentionDecodeWithKVCacheFwdOp': {'mha_decode_kernel': 'tileops.kernels.attention.mha_decode:MHADecodeKernel'},
    'MultiHeadAttentionFwdOp': {
        'gqa_prefill_causal_fwd_kernel': 'tileops.kernels.attention.gqa_prefill_fwd_ws:GQAPrefillFwdWsPersistentCausalKernel',
        'gqa_prefill_fwd_kernel': 'tileops.kernels.attention.gqa_fwd:GQAPrefillFwdKernel',
        'gqa_prefill_square_fwd_kernel': 'tileops.kernels.attention.gqa_fwd_ws:GQAFwdWsPersistentCausalKernel',
    },
    'MultiHeadLatentAttentionDecodeWithKVCacheFwdOp': {'mla_decode_kernel': 'tileops.kernels.attention.deepseek_mla_decode:MLADecodeWsKernel'},
    'NanToNumFwdOp': {'nan_to_num': 'tileops.kernels.elementwise:NanToNumFwdKernel'},
    'NeFwdOp': {'ne': 'tileops.kernels.elementwise:NeFwdKernel'},
    'NegFwdOp': {'neg': 'tileops.kernels.elementwise:NegFwdKernel'},
    'PowFwdOp': {'pow': 'tileops.kernels.elementwise:PowFwdKernel'},
    'PreluFwdOp': {'prelu': 'tileops.kernels.elementwise:PreluFwdKernel'},
    'ProdFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'RMSNormFwdOp': {'rms_norm': 'tileops.kernels.norm.rms_norm:RMSNormKernel'},
    'ReciprocalFwdOp': {'reciprocal': 'tileops.kernels.elementwise:ReciprocalFwdKernel'},
    'ReluFwdOp': {'relu': 'tileops.kernels.elementwise:ReluFwdKernel'},
    'RemainderFwdOp': {'remainder': 'tileops.kernels.elementwise:RemainderFwdKernel'},
    'RopeLlama31Op': {'rope_llama31': 'tileops.kernels.rope:RopeLlama31Kernel'},
    'RopeLongRopeOp': {'rope_longrope': 'tileops.kernels.rope:RopeLongRopeKernel'},
    'RopeNeoxOp': {'rope_neox': 'tileops.kernels.rope:RopeNeoxKernel'},
    'RopeNeoxPositionIdsOp': {'rope_neox_position_ids': 'tileops.kernels.rope:RopeNeoxPositionIdsKernel'},
    'RopeNonNeoxOp': {'rope_non_neox': 'tileops.kernels.rope:RopeNonNeoxKernel'},
    'RopeYarnOp': {'rope_yarn': 'tileops.kernels.rope:RopeYarnKernel'},
    'RoundFwdOp': {'round': 'tileops.kernels.elementwise:RoundFwdKernel'},
    'RsqrtFwdOp': {'rsqrt': 'tileops.kernels.elementwise:RsqrtFwdKernel'},
    'SSDChunkScanFwdOp': {'ssd_chunk_scan_fwd': 'tileops.kernels.mamba.ssd_chunk_scan:SSDChunkScanFwdKernel'},
    'SSDChunkStateFwdOp': {'ssd_chunk_state_fwd': 'tileops.kernels.mamba.ssd_chunk_state:SSDChunkStateFwdKernel'},
    'SSDChunkStateSeqIdxFwdOp': {'ssd_chunk_state_fwd': 'tileops.kernels.mamba.ssd_chunk_state:SSDChunkStateFwdKernel'},
    'SSDDecodeOp': {'ssd_decode': 'tileops.kernels.mamba.ssd_decode:SSDDecodeKernel'},
    'SSDStatePassingFwdOp': {'ssd_state_passing_fwd': 'tileops.kernels.mamba.ssd_state_passing:SSDStatePassingFwdKernel'},
    'SSDStatePassingInitStatesFwdOp': {'ssd_state_passing_fwd': 'tileops.kernels.mamba.ssd_state_passing:SSDStatePassingFwdKernel'},
    'SeluFwdOp': {'selu': 'tileops.kernels.elementwise:SeluFwdKernel'},
    'SigmoidFwdOp': {'sigmoid': 'tileops.kernels.elementwise:SigmoidFwdKernel'},
    'SignFwdOp': {'sign': 'tileops.kernels.elementwise:SignFwdKernel'},
    'SiluAndMulFwdOp': {'silu_and_mul': 'tileops.kernels.elementwise:SiluAndMulFwdKernel'},
    'SiluFwdOp': {'silu': 'tileops.kernels.elementwise:SiluFwdKernel'},
    'SinFwdOp': {'sin': 'tileops.kernels.elementwise:SinFwdKernel'},
    'SinusoidalFwdOp': {'sinusoidal': 'tileops.kernels.elementwise:SinusoidalFwdKernel'},
    'SoftmaxFwdOp': {'softmax_fwd': 'tileops.kernels.reduction.softmax:SoftmaxKernel'},
    'SoftplusFwdOp': {'softplus': 'tileops.kernels.elementwise:SoftplusFwdKernel'},
    'SqrtFwdOp': {'sqrt': 'tileops.kernels.elementwise:SqrtFwdKernel'},
    'StdFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'SubFwdOp': {'sub': 'tileops.kernels.elementwise:SubFwdKernel'},
    'SumFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'TanhFwdOp': {'tanh': 'tileops.kernels.elementwise:TanhFwdKernel'},
    'TopkSelectorOp': {'topk_selector_kernel': 'tileops.kernels.topk_selector:TopkSelectorKernel'},
    'TruncFwdOp': {'trunc': 'tileops.kernels.elementwise:TruncFwdKernel'},
    'VarFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'VarMeanFwdOp': {'reduce': 'tileops.kernels.reduction.reduce:ReduceKernel'},
    'WhereFwdOp': {'where': 'tileops.kernels.elementwise:WhereFwdKernel'},
}
